// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:bin': typeof import('~icons/carbon/bin')['default']
    'Carbon:delete': typeof import('~icons/carbon/delete')['default']
    'Carbon:edit': typeof import('~icons/carbon/edit')['default']
    'Carbon:language': typeof import('~icons/carbon/language')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'Carbon:moon': typeof import('~icons/carbon/moon')['default']
    'Carbon:sun': typeof import('~icons/carbon/sun')['default']
    'Carbon:tra': typeof import('~icons/carbon/tra')['default']
    'Carbon:tradioPushToTalk': typeof import('~icons/carbon/tradio-push-to-talk')['default']
    'Carbon:trash': typeof import('~icons/carbon/trash')['default']
    'Carbon:trashCan': typeof import('~icons/carbon/trash-can')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CardUtil: typeof import('./src/components/CardUtil.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PeopleListItem: typeof import('./src/components/PeopleListItem.vue')['default']
    TeamCard: typeof import('./src/components/TeamCard.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UtilCard: typeof import('./src/components/UtilCard.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

export { }
