// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppAddButton: typeof import('./src/components/AppAddButton.vue')['default']
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppForm: typeof import('./src/components/AppForm.vue')['default']
    AppHeading: typeof import('./src/components/AppHeading.vue')['default']
    AppInput: typeof import('./src/components/AppInput.vue')['default']
    AppLoading: typeof import('./src/components/AppLoading.vue')['default']
    BrandName: typeof import('./src/components/BrandName.vue')['default']
    'Carbon:3dCursorAlt': typeof import('~icons/carbon/3d-cursor-alt')['default']
    'Carbon:add': typeof import('~icons/carbon/add')['default']
    'Carbon:arrowLeft': typeof import('~icons/carbon/arrow-left')['default']
    'Carbon:circleDash': typeof import('~icons/carbon/circle-dash')['default']
    'Carbon:edit': typeof import('~icons/carbon/edit')['default']
    'Carbon:trashCan': typeof import('~icons/carbon/trash-can')['default']
    DoubleFieldFormContainer: typeof import('./src/components/DoubleFieldFormContainer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainNavigationBar: typeof import('./src/components/MainNavigationBar.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PeopleList: typeof import('./src/components/PeopleList.vue')['default']
    PeopleListItem: typeof import('./src/components/PeopleListItem.vue')['default']
    PeopleListItemTeamIcon: typeof import('./src/components/PeopleListItemTeamIcon.vue')['default']
    PhoneNumberInput: typeof import('./src/components/PhoneNumberInput.vue')['default']
    TeamsList: typeof import('./src/components/TeamsList.vue')['default']
    TeamsListItem: typeof import('./src/components/TeamsListItem.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
  }
}

export { }
