import { userAddressMock } from './usersAddress'

export const mockUsers = [
  {
    url: 'https://xsgames.co/randomusers/assets/avatars/male/24.jpg',
    id: 1,
    fullName: 'Staffy de Nielden',
    displayName: 'Staffy',
    initials: 'SN',
    email: 'staff_1@venue.com',
    phoneNumber: '68872901',
    phoneCountryPrefix: '+31',
    teamIds: [1, 3],
    image: 'image1.png',
    address: userAddressMock[1],
    isEmployee: true,
    xc: '1st Chef',
    userPermissions: []
  },
  {
    url: 'xsgames.co/randomusers/avatar.php?g=female/24.jpg',
    id: 2,
    fullName: 'Jenny Smith',
    displayName: 'Jenny',
    initials: 'JS',
    email: 'jenny_2@venue.com',
    phoneNumber: '68872902',
    phoneCountryPrefix: '+31',
    teamIds: [2, 4],
    image: 'image2.png',
    address: userAddressMock[2],
    isEmployee: true,
    xc: '2nd Chef',
    userPermissions: []
  },
  {
    url: 'https://xsgames.co/randomusers/assets/avatars/male/43.jpg',
    id: 3,
    fullName: 'John Doe',
    displayName: 'John',
    initials: 'JD',
    email: 'john_3@venue.com',
    phoneNumber: '68872903',
    phoneCountryPrefix: '+31',
    teamIds: [1, 2],
    image: 'image3.png',
    address: userAddressMock[3],
    isEmployee: true,
    xc: '3rd Chef',
    userPermissions: []
  },
  {
    url: 'xsgames.co/randomusers/avatar.php?g=female/77.jpg',
    id: 4,
    fullName: 'Sarah Johnson',
    displayName: 'Sarah',
    initials: 'SJ',
    email: 'sarah_4@venue.com',
    phoneNumber: '68872904',
    phoneCountryPrefix: '+31',
    teamIds: [3, 4],
    image: 'image4.png',
    address: userAddressMock[4],
    isEmployee: true,
    xc: '4th Chef',
    userPermissions: []
  },
  {
    url: 'https://xsgames.co/randomusers/assets/avatars/male/26.jpg',
    id: 5,
    fullName: 'Michael Brown',
    displayName: 'Michael',
    initials: 'MB',
    email: 'michael_5@venue.com',
    phoneNumber: '68872905',
    phoneCountryPrefix: '+31',
    teamIds: [2, 3],
    image: 'image5.png',
    address: userAddressMock[5],
    isEmployee: true,
    xc: '5th Chef',
    userPermissions: []
  },
  {
    url: 'https://xsgames.co/randomusers/assets/avatars/male/33.jpg',
    id: 6,
    fullName: 'Emily Davis',
    displayName: 'Emily',
    initials: 'ED',
    email: 'emily_6@venue.com',
    phoneNumber: '68872906',
    phoneCountryPrefix: '+31',
    teamIds: [1, 4],
    image: 'image6.png',
    address: userAddressMock[6],
    isEmployee: true,
    xc: '6th Chef',
    userPermissions: []
  }
]
